Built an APK from this version of code and it works on my A13 Lollipop 5.1 even though it the app doesn't work in either of the API22 emulators.  Increasing the VM heap size from 80MB to 2GB didn't help
LogCat flagged:

Caused by: android.content.res.Resources$NotFoundException: File res/color/radio_bg_f58027_alpha.xml from drawable resource ID #0x7f0503ba

which exists and is in the correct location,

and

org.xmlpull.v1.XmlPullParserException: Binary XML file line #3: <item> tag requires a 'drawable' attribute or child tag defining a drawable

will commit and push this version, then try:
Clean Project
Rebuild Project